# Generated by Django 3.1.1 on 2020-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('mobileno', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=1000)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_timing', models.CharField(default='900', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GuestSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.CharField(default='15', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Page_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.CharField(default='12', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='password_verify_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=250)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
