# Generated by Django 3.1.1 on 2020-09-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200914_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profiles'),
        ),
    ]
