# Generated by Django 3.1.1 on 2020-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200914_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profiles'),
        ),
    ]
