# Generated by Django 3.1.1 on 2020-09-12 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('superuser', models.BooleanField(default=False)),
                ('addvideo', models.BooleanField(default=False)),
                ('addcategory', models.BooleanField(default=False)),
                ('addlanguage', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('joined', models.BooleanField(default=False)),
            ],
        ),
    ]
